#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l walltime=10:00:00
#PBS -l vmem=20gb

# Make output directories
mkdir -p output
mkdir -p out_figs
mkdir -p out_dir_report

# export SUBJECTS_DIR="$(dirname "$out_dir")"

# singularity exec -e docker://brainlife/mne-freesurfer:7.3.2-1.2.1 python3 main.py

singularity  exec --env FS_LICENSE=${FS_LICENSE} -e docker://brainlife/mne-freesurfer:7.3.2-1.2.1 python3 main.py

# singularity exec -e docker://brainlife/mne-freesurfer:7.3.2-1.2.1 mne watershed_bem
