#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:10:00

set -x
set -e

# Make output directories
mkdir -p out_dir
mkdir -p out_figs
mkdir -p out_dir_report

#export SUBJECTS_DIR="$(dirname "$out_dir")"

singularity exec -e docker://brainlife/mne-freesurfer python3 main.py

#singularity exec -e docker://brainlife/mne-freesurfer:7.3.2-1.2.1 mne watershed_bem
